CREATE OR REPLACE FUNCTION FNC_VALIDA(pTIPO     IN NUMBER,
                                      pSUBTIPO  IN NUMBER)
RETURN VARCHAR
AS
 vVALIDA   VARCHAR2(50);
 vRETORNO  VARCHAR2(50);
BEGIN

 SELECT NVL(N.NATUREZA ,0) NREG
   INTO vVALIDA
   FROM OM_RECORD_NATUREZA N
  WHERE N.TIPO    = pTIPO
    AND N.SUBTIPO = pSUBTIPO;
    
 IF vVALIDA  <> 0 THEN
    vRETORNO := vVALIDA;
 ELSE 
    vRETORNO := 0;
 END IF;
 
RETURN vRETORNO;
 
END;