CREATE OR REPLACE TRIGGER TRG_TCALL
AFTER INSERT
   ON TCALL
   FOR EACH ROW

DECLARE
   vDECIDE  NUMBER := 0;

BEGIN

   SELECT FNC_VALIDA(:NEW.TIPO, :NEW.SUBTIPO) INTO vDECIDE FROM DUAL; 
   
   IF vDECIDE <> 0 THEN
      NULL;
   END IF;

   INSERT INTO OM_RECORD
   (OID
   ,TIPO
   ,SUBTIPO
   ,NATUREZA
   ,DATA_CRIACAO)
   VALUES
   ( SEQ_OM_RECORD.NEXTVAL,  -- SEQUENCIAL
     :new.TIPO,              -- IGUAL DA TCALL
     :new.SUBTIPO,           -- IGUAL DA TCALL
     CASE WHEN vDECIDE <> 0 THEN vDECIDE
          ELSE 0
     END,
     SYSDATE                 -- DATA ATUAL
    );

END;