-- 8.Informações sobre animais de estimação são 
-- mantidos em duas tabelas separadas:

CREATE TABLE DOGS(id INTEGER NOT NULL PRIMARY KEY,
                  name VARCHAR(50) NOT NULL);
INSERT INTO DOGS VALUES(4, 'PITBULL');
INSERT INTO DOGS VALUES(5, 'POODLE');
INSERT INTO DOGS VALUES(7, 'ILHASA');
COMMIT;

CREATE TABLE CATS(id INTEGER NOT NULL PRIMARY KEY,
                  name VARCHAR(50) NOT NULL);

INSERT INTO CATS VALUES(4, 'SIAMES');
INSERT INTO CATS VALUES(5, 'GARFIELD');
INSERT INTO CATS VALUES(7, 'BORMILA');
COMMIT;
-- Escreva uma consulta SQL que selecione o nome de todos 
-- os animais de estimação de maneira distinta.

-- LISTANDO NOME DOS ANIMAIS DE FORMA DISTINTAS
SELECT NAME AS RACA
     , COUNT(NAME) TOTAL_POR_RACA
  FROM CATS
  GROUP BY NAME
UNION
SELECT NAME AS RACA
     , COUNT(NAME) TOTAL_POR_RACA
  FROM DOGS
  GROUP BY NAME;

--SELECT * FROM DOGS;
--SELECT * FROM CATS;
SELECT DISTINCT NAME
  FROM CATS
  GROUP BY NAME
UNION
SELECT DISTINCT NAME
  FROM DOGS
  GROUP BY NAME;