-- EXERCÍCIO 10
RESPOSTA : NA MESMA SEÇÃO RESULTADO: 1
         : EM OUTRA SEÇÃO RESULTADO: 0 POIS NÃO HOUVE COMMIT, A TRANSAÇÃO
           FICA VISÍVEL SOMENTE NA SEÇÃO AGUARDANDO COMMIT OU ROLLBACK;